services:
  streamlit:
    build: .
    container_name: streamlit-rescue-predict
    ports:
      - "7860:7860"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    volumes:
      - .:/app
    restart: always
